export type Gender = "women" | "men"
export type Category =
  | "earrings"
  | "necklaces"
  | "bracelets"
  | "rings"
  | "anklets"
  | "bangles"
  | "pendants"
  | "sets"
  | "studs"
  | "chains"
  | "cufflinks"
  | "custom"

export interface Product {
  id: string
  name: string
  category: Category
  price: number
  originalPrice?: number
  image: string
  images: string[]
  description: string
  material: string
  weight: string
  rating: number
  reviews: number
  inStock: boolean
  bestseller?: boolean
  featured?: boolean
  gender?: Gender
  style?: "minimalistic" | "statement" | "traditional" | "modern"
  occasion?: "daily wear" | "party" | "gifting"
  materialType?: "pure silver" | "oxidized" | "silver with gemstones"
  newArrival?: boolean
}

export const GENDER_TYPES: Record<Gender, Category[]> = {
  women: [
    "earrings",
    "necklaces",
    "bracelets",
    "rings",
    "anklets",
    "bangles",
    "pendants",
    "sets",
  ],
  men: ["rings", "studs", "bracelets", "chains", "cufflinks", "pendants", "sets"],
}

// Single "Elite" set that combines both previous gender lists (unique)
export const ELITE_TYPES: Category[] = Array.from(
  new Set([...(GENDER_TYPES.women || []), ...(GENDER_TYPES.men || [])])
)

// Example catalogue for integration and dynamic filters
export const products: Product[] = [
  {
    id: "w-earring-1",
    name: "earring",
    category: "earrings",
    price: 0,
    image: "/oxidized-jhumka.jpg",
    images: ["/oxidized-jhumka.jpg"],
    description: "Traditional oxidized jhumkas with intricate carving.",
    material: "925 Sterling Silver",
    weight: "6.2g",
    rating: 4.6,
    reviews: 41,
    inStock: true,
    gender: "women",
    style: "traditional",
    occasion: "party",
    materialType: "oxidized",
    newArrival: true,
  },
  {
    id: "w-necklace-1",
    name: "necklace",
    category: "necklaces",
    price: 0,
    image: "/minimal-bar-necklace.jpg",
    images: ["/minimal-bar-necklace.jpg"],
    description: "Sleek bar pendant for everyday elegance.",
    material: "925 Sterling Silver",
    weight: "3.1g",
    rating: 4.7,
    reviews: 58,
    inStock: true,
    gender: "women",
    style: "minimalistic",
    occasion: "daily wear",
    materialType: "pure silver",
    bestseller: true,
  },
  {
    id: "w-bracelet-1",
    name: "bracelet",
    category: "bracelets",
    price: 0,
    image: "/gemstone-charm-bracelet.jpg",
    images: ["/gemstone-charm-bracelet.jpg"],
    description: "Delicate bracelet accented with colored gemstones.",
    material: "925 Sterling Silver",
    weight: "4.0g",
    rating: 4.5,
    reviews: 26,
    inStock: true,
    gender: "women",
    style: "modern",
    occasion: "gifting",
    materialType: "silver with gemstones",
  },
  {
    id: "w-ring-1",
    name: "ring",
    category: "rings",
    price: 0,
    image: "/stacked-silver-rings.jpg",
    images: ["/stacked-silver-rings.jpg"],
    description: "Set of slim stackable rings for layered looks.",
    material: "925 Sterling Silver",
    weight: "2.0g",
    rating: 4.8,
    reviews: 112,
    inStock: true,
    gender: "women",
    style: "minimalistic",
    occasion: "daily wear",
    materialType: "pure silver",
    bestseller: true,
  },
  {
    id: "w-anklet-1",
    name: "anklet",
    category: "anklets",
    price: 0,
    image: "/beaded-silver-anklet.jpg",
    images: ["/beaded-silver-anklet.jpg"],
    description: "Playful anklet with silver beads.",
    material: "925 Sterling Silver",
    weight: "3.6g",
    rating: 4.4,
    reviews: 19,
    inStock: true,
    gender: "women",
    style: "modern",
    occasion: "party",
    materialType: "pure silver",
  },
  {
    id: "w-bangle-1",
    name: "bangle",
    category: "bangles",
    price: 0,
    image: "/hammered-silver-bangle.jpg",
    images: ["/hammered-silver-bangle.jpg"],
    description: "Statement bangle with hammered texture.",
    material: "925 Sterling Silver",
    weight: "10.2g",
    rating: 4.6,
    reviews: 34,
    inStock: true,
    gender: "women",
    style: "statement",
    occasion: "party",
    materialType: "pure silver",
  },
  {
    id: "w-pendant-1",
    name: "pendant",
    category: "pendants",
    price: 0,
    image: "/silver-pearl-pendant.jpg",
    images: ["/silver-pearl-pendant.jpg"],
    description: "Elegant floral motif with gemstone center.",
    material: "925 Sterling Silver",
    weight: "2.4g",
    rating: 4.5,
    reviews: 22,
    inStock: true,
    gender: "women",
    style: "traditional",
    occasion: "gifting",
    materialType: "silver with gemstones",
  },
  {
    id: "w-set-1",
    name: "set",
    category: "sets",
    price: 0,
    image: "/silver-set-pendant-studs.jpg",
    images: ["/silver-set-pendant-studs.jpg"],
    description: "Coordinated pendant with matching studs.",
    material: "925 Sterling Silver",
    weight: "6.8g",
    rating: 4.7,
    reviews: 44,
    inStock: true,
    gender: "women",
    style: "modern",
    occasion: "gifting",
    materialType: "pure silver",
    newArrival: true,
  },
  {
    id: "m-ring-1",
    name: "ring",
    category: "rings",
    price: 0,
    image: "/bold-signet-ring.jpg",
    images: ["/bold-signet-ring.jpg"],
    description: "Classic signet ring with a polished finish.",
    material: "925 Sterling Silver",
    weight: "7.5g",
    rating: 4.6,
    reviews: 63,
    inStock: true,
    gender: "men",
    style: "statement",
    occasion: "party",
    materialType: "pure silver",
    bestseller: true,
  },
  {
    id: "m-studs-1",
    name: "stud",
    category: "studs",
    price: 0,
    image: "/minimal-studs.jpg",
    images: ["/minimal-studs.jpg"],
    description: "Simple silver studs for understated style.",
    material: "925 Sterling Silver",
    weight: "1.2g",
    rating: 4.3,
    reviews: 15,
    inStock: true,
    gender: "men",
    style: "minimalistic",
    occasion: "daily wear",
    materialType: "pure silver",
  },
  {
    id: "m-bracelet-1",
    name: "bracelet",
    category: "bracelets",
    price: 0,
    image: "/box-link-bracelet.jpg",
    images: ["/box-link-bracelet.jpg"],
    description: "Sturdy box link bracelet for everyday wear.",
    material: "925 Sterling Silver",
    weight: "12.0g",
    rating: 4.5,
    reviews: 37,
    inStock: true,
    gender: "men",
    style: "modern",
    occasion: "daily wear",
    materialType: "pure silver",
  },
  {
    id: "m-chain-1",
    name: "chain",
    category: "chains",
    price: 0,
    image: "/delicate-silver-chain.jpg",
    images: ["/delicate-silver-chain.jpg"],
    description: "Classic Figaro chain in 20-inch length.",
    material: "925 Sterling Silver",
    weight: "9.8g",
    rating: 4.7,
    reviews: 51,
    inStock: true,
    gender: "men",
    style: "modern",
    occasion: "party",
    materialType: "pure silver",
  },
  {
    id: "m-cufflinks-1",
    name: "cufflink",
    category: "cufflinks",
    price: 0,
    image: "/geometric-cufflinks.jpg",
    images: ["/geometric-cufflinks.jpg"],
    description: "Angular cufflinks with brushed finish.",
    material: "925 Sterling Silver",
    weight: "5.0g",
    rating: 4.4,
    reviews: 18,
    inStock: true,
    gender: "men",
    style: "modern",
    occasion: "gifting",
    materialType: "pure silver",
  },
  {
    id: "m-pendant-1",
    name: "pendant",
    category: "pendants",
    price: 0,
    image: "/dog-tag-pendant.jpg",
    images: ["/dog-tag-pendant.jpg"],
    description: "Minimal dog tag pendant with optional engraving.",
    material: "925 Sterling Silver",
    weight: "6.1g",
    rating: 4.5,
    reviews: 23,
    inStock: true,
    gender: "men",
    style: "minimalistic",
    occasion: "gifting",
    materialType: "pure silver",
  },
  {
    id: "custom-1",
    name: "custom",
    category: "custom",
    price: 0,
    image: "/custom-name-silver-ring.jpg",
    images: [
      "/custom-name-ring-front.jpg",
      "/custom-name-ring-side.jpg",
      "/custom-name-ring-detail.jpg",
    ],
    description:
      "Personalize your jewellery with a custom engraved name ring. Handcrafted to order in certified 925 silver.",
    material: "925 Sterling Silver",
    weight: "3.5g",
    rating: 4.9,
    reviews: 203,
    inStock: true,
    bestseller: true,
    gender: "women",
    style: "modern",
    occasion: "gifting",
    materialType: "pure silver",
    newArrival: true,
  },
]
